### ISSUE TITLE
Missing search params: _count is undefined

### ISSUE THREAD

**Issue by PedroS11** [Asymmetrik/node-fhir-server-core#104]
Hello, I'm trying to get the __count_ value from the search params however after some search on the source code, I found that only part of the following params are implemented

	let { _INCLUDE, _REVINCLUDE, _SORT, _COUNT, _SUMMARY, _ELEMENTS, _CONTAINED, _CONTAINEDTYPED } = args;

According to your file _common.arguments.js_, only some of them are implemented and I want to use the __count_. how should I do without changing the source code?

**Comment by jonterrylee** [comment]
Hi @PedroS11 

If you have noticed that we're missing parameters that should be supported, feel free to create a PR or let us know if we can take care of it.  I have a made a PR for _count since that is something we should be supporting [#105](https://github.com/Asymmetrik/node-fhir-server-core/pull/105).  Most of these files are auto generated, so we'll need to make sure our generator is accounting for them.  

If they are common parameters, feel free to add it to the common args file, if it's resource specific, add them to the resource argument specific file.

Thanks for letting us know.

**Comment by PedroS11** [comment]
Ok, I will wait for the PR to be accepted because that's what I need. But for now, I will add it temporarily and when the pr is accepted I will use the newer version. Thank you and let me know when there's any news.

**Comment by PedroS11** [comment]
@jonterrylee Any eta for the PR to be accepted?

**Comment by jonterrylee** [comment]
@PedroS11 

Check out  [Tag 1.2.2](https://github.com/Asymmetrik/node-fhir-server-core/releases/tag/1.2.2) [PR 105](https://github.com/Asymmetrik/node-fhir-server-core/pull/105).  We've added additional search parameters.  

Let us know if you have any issues.

Thanks

**Comment by PedroS11** [comment]
It's nice now. Thank you so much, you can close this now :D
