### ISSUE TITLE
Define a custom search parameter?

### ISSUE THREAD

**Issue by bryanvanhoorn** [Asymmetrik/node-fhir-server-core#109]
Is it possible to define a custom search parameter for a particular profile?  In my case, I would like to add an endDateTime as a parameter when searching for Slots.  However, this parameter is getting removed by the arg sanitizer because it is not listed in the FHIR spec.  Is there a way to specify that I would like to allow this custom parameter through?  Thank you!

**Comment by jonterrylee** [comment]
@bryanvanhoorn 

I've added my initially support for custom arguments.  We're still thinking this through so this may not be the final implementation.  

Check out this [branch](https://github.com/Asymmetrik/node-fhir-server-core/tree/feature/custom-arguments)

Specifically this file [slot.arguments.js](https://github.com/Asymmetrik/node-fhir-server-core/blob/feature/custom-arguments/src/server/profiles/slot/slot.arguments.js)

**Comment by Robert-W** [comment]
@jonterrylee Where are we on this? If we can support this and we want to merge this in, we should add this to #119 and get some documentation on this.

**Comment by dominathan** [comment]
I will need this to not be working off my fork as I have custom params.

**Comment by elementechemlyn** [comment]
I've been looking at custom arguments myself recently - and thinking that it would be useful to remove them as well as add additional ones.

It doesn't quite seem right to "sanitise" the arguments to a list that may not be supported by the specific service implementation so I was wondering whether adding an optional SearchParameters object to the service may be the way to go? The configureResourceRoutes function in route_setter could then use those if they exist or fallback to the builtin set if not? It would also keep local customisation out of the main code tree.

**Comment by elementechemlyn** [comment]
I've implemented this in my fork. If the team agree it's sensible I can submit a PR (although I can't see a develop branch at the moment?).

**Comment by Robert-W** [comment]
Hey @elementechemlyn, sorry about that we are a little behind because of the holidays on updating documentation. We have removed develop recently since we are now publishing this to npm and it was just causing things to be out of sync (patches pushed directly to master and getting overriden when develop was merged back in). This means installing and versioning is much easier and safer.

You can submit your PR to master, we are going to change the documentation soon to encourage people to install from npm and not master where we can more easily control releases.

We have a priority task today to go through the Wiki and [Contributors guide](https://github.com/Asymmetrik/node-fhir-server-core/blob/master/.github/CONTRIBUTING.md) and get all these things updated.

**Comment by Robert-W** [comment]
Closing for now, feel free to reopen or post a question on StackOverflow with the tags `node-fhir-server-core` or `javascript-fhir`.
