### ISSUE TITLE
Querying by entity references (v3)

### ISSUE THREAD

**Issue by kalihos** [Asymmetrik/node-fhir-server-core#141]
Hello,

I'm unable to get a query from my FHIR server: I simply want to get all appointments for a single day, for a single patient. As date filtering is simple, because I need only to query by a string...

https://server:port/3_0_1/Appointment?date=2018-10-29&status=booked

...I can't get the patient filter, because it's a reference. If I'm not wrong, watching official documentation (http://hl7.org/fhir/search.html), it should be something like...

https://server:port/3_0_1/Appointment?date=2018-10-29&status=booked&patient:Patient=295

But I get a "Invalid parameter: patient". My appointment "search" service is defined:

...
let patient = args['patient'];
...
if (patient) {
	query += " and p.idpaciente = " + patient;
};

Am I doing anything wrong? I get similar errors even when referencing a complex object from the same entity...

Thank you very much.

**Comment by Robert-W** [comment]
Hi @kalihos, You are correct and this is an unfortunate limitation in some of the older versions of the parameter sanitizer. I tested http://localhost:3000/3_0_1/Appointment?date=2018-10-29&status=booked&patient:Patient=295 on the current master branch and it seems to allow it through. When I log the args going through I see the following:

```json
{
  "base_version": "3_0_1",
  "date": "2018-10-29",
  "patient:Patient": "295",
  "status": "booked"
}
```

Are you able to upgrade to the latest version by chance?

On a side note, the sanitizer is something else that we are rebuilding in our [phx-tools](https://github.com/Asymmetrik/phx-tools) repo to support modifiers, custom params, and much more. We currently fail on parameters we do not understand (the older version does not understand many params which is why the error you are seeing used to happen much more). The master branch understands much more. The new version, which will unfortunately be a breaking change, wont fail unless a parameter we know the type for is in violation, unknown ones will still get passed and won't fail like how we do currently

**Comment by kalihos** [comment]
Hi @Robert-W,

I've upgraded the server to your new 6 days ago version. And it's true that I get those args, thank you!

And it works perfectly!!! You're great!

All I have to do to access that parameter is changing my access method for that variable, by this one:

console.log(args["patient:Patient"])

I will deeply test this new version, but it looks great!

Thank you very much again.

**Comment by Robert-W** [comment]
Your welcome, let me know if there is anything else we can help you with !!!
