### ISSUE TITLE
How to add custom route ?

### ISSUE THREAD

**Issue by awais786327** [Asymmetrik/node-fhir-server-core#163]
### Not able to call custom route

![image](https://user-images.githubusercontent.com/12613564/56078675-46aaf580-5e04-11e9-87ce-4eddd42a11ad.png)

I have registered **auth route** like shown in image but i am not able to view or call this route

it is giving **404** not found

![image](https://user-images.githubusercontent.com/12613564/56078780-68f14300-5e05-11e9-97d5-e3849637fdb8.png)

please tell me how to do this ?

**Comment by Robert-W** [comment]
Hi @awais786327,

We are trying to shift questions to Stack Overflow to make questions and answers easier for others to discover. In the future, could you please post questions there with the tag `node-fhir-server-core` or `javascript-fhir` and we can answer them on Stack Overflow.

The reason you are getting a 404 is that `FHIRServer.initialize(config)` calls several functions, including setting up a catch all error handler. Any routes added after initialize will not ever be reached because of the way express adds routes.

What you can do, is not call initialize but call the functions it calls internally yourself, something like this:

```javascript
const { Server } = require('@asymmetrik/node-fhir-server-core');

let server = new Server(config);

// Write your own custom middleware here for validating roles or using passport
server.app.use(function (req, res, next) {
	
});

// This is everything initialize calls except configurePassport
server.configureMiddleware()
	.configureSession()
	.configureHelmet()
	.setPublicDirectory()
	.setProfileRoutes()
	.setErrorRoutes();

server.listen(3000);
```

You can read more on that here: https://github.com/Asymmetrik/node-fhir-server-core/wiki/Access-Control#how-to-customize.
