### ISSUE TITLE
usage of _include and _revinclude search params

### ISSUE THREAD

**Issue by anandanguru** [Asymmetrik/node-fhir-server-core#164]
Any update on how to use Search params with _include and _revinclude params...??

**Comment by Robert-W** [comment]
Hi @anandanguru,

In the future, please ask questions on Stack Overflow with either the tag `javascript-fhir` or `node-fhir-server-core`.  It makes it easier for others with the same question to find the answer's and it makes issues better for tracking bugs and feature requests.

It's on our roadmap to add back some support for common parameters to all endpoints (not sure the current ETA since we have some other deadlines we need to meet). If you would like to submit a PR we would appreciate it.  In the meantime, you can modify any of the parameter files and add a section in for this. At that point, you just write your own query.

For example, add an entry to the `src/server/standards/4_0_0/arguments/patient.arguments.js`:

```javascript
_include: {
  type: 'string',
  fhirtype: 'string',
  // The extra fields are not necessary, just there to help for building queries if needed
},
```

And it will now work, if you want it on all resources, add it to the `src/server/standards/4_0_0/arguments/resource.arguments.js` file.

**Comment by Robert-W** [comment]
Closing for now, if you are having trouble developing an implementation, feel free to post a question on StackOverflow and we would be glad to help.
