### ISSUE TITLE
Add TypeScript types to DefinitelyTyped

### ISSUE THREAD

**Issue by joepaquette** [Asymmetrik/node-fhir-server-core#186]
### Do you want to request a feature, report a bug, or improve documentation?
New Feature

For Typescript developers, it would be very helpful if you would contribute the type definitions for this packages to DefinitelyTyped (https://definitelytyped.org).

**Comment by Robert-W** [comment]
Hey @joepaquette, sorry for the delayed response, I've been a little busy the past few weeks and haven't had much time to get back to this. 

We don't currently have type definitions generated for FHIR resources. They do have them already supported for STU3, but nothing yet for R4. Internally for this project we do not use TypeScript, so this has been lower priority for us, but we have had several inquiries about it soI can bring this up when we get around to our next sprint on open source work.

If we did do this, we would more than likely publish definitions to Definitely Typed and advertise them here, but not include them by default. Meaning for TS devs, they would just need to add them via npm and they would be good.

**Comment by navndn** [comment]
Any update on this?

**Comment by Ahryman40k** [comment]
Have you take a look at [this](https://medium.com/@ahryman40k/typescript-fhir-r4-server-e50f0a9250ca) ?

**Comment by jacklinton** [comment]
@Robert-W I notice that you use JSDoc comments to provide basic type definitions in your code. Since Typescript version 3.7 I believe, the Typescript cli gives you the option to emit type declaration files for plain JS using the JSDoc type definitions. It can be integrated in your CI process to produce the declaration file(s) when you publish updates to NPM or what have you.

@joepaquette in the meantime you could use that feature to create a Typescript config to go into server core package in node_modules and create a type declaration file for you immediately using the types that Asymmetrik provides in their JSDoc comments.

Doing this would integrate the Typescript language service in the developers' IDE and would make interfacing with the core as a developer much easier as you would have instant access to function signatures and the like despite the lack of formal documentation on the underlying code.

Thanks for your great work Asymmetrik! The folks from the US Gov developing the BlueButton software had nothing but great things to say about your team's work. It's a significant contribution to the Javascript community and I can't praise you enough for it.

**Comment by luan-dev** [comment]
DefinitelyTyped added support for r4: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/fhir
